baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
[cascade._build]
    publishResources = false