baseURL = "https://wsvgny.github.io/blog/"
languageCode = "en-us"
title = "William Sevigny"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
[cascade._build]
    publishResources = false